version: '3.4'
services:
 eureka-service:
   build:
     context: eureka-service
     dockerfile: Dockerfile
   ports:
     - '8761:8761'

 authentication-service:
   build:
     context: authentication-service
     dockerfile: Dockerfile
   ports:
     - '8081:8081'
   depends_on:
     - eureka-service
     - mysql

 search-service:
   build:
     context: search-service
     dockerfile: Dockerfile
   ports:
     - '8082:8082'
   depends_on:
     - eureka-service
     - mysql

 mysql:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: 'lab1'
     MYSQL_USER: 'root'
     MYSQL_PASSWORD: 'root'
     MYSQL_ROOT_PASSWORD: 'root'
   ports:
     - '3306:3306'

 api-gateway:
   build:
     context: api-gateway
     dockerfile: Dockerfile
   ports:
     - '8080:8080'
   depends_on:
     - authentication-service
     - search-service